name: Changed files

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@v38
        
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: Show all changed files
        if: steps.changed-files.outputs.all_any_changed == 'true'
        run: |
          echo "the following files were changed: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

