name: Create comment
          
on:
  pull_request:

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Print hello
        id: print-hello
        run: |
          python .github/scripts/hello_world.py > ./comment

      - name: Show hello
        id: show-hello
        run: |
          cat ./comment
  
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }} 
          body-path: ./comment