name: Show matrix

on:
  workflow_dispatch:

jobs:
  compile-mex:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-13, macos-14, windows-2019, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
        - name: Show matrix details
          run: |
            echo "OS: ${{ matrix.os }}"
            uname -a
          shell: bash