name: Run Default Tasks in Build File
on:
    workflow_dispatch:

jobs:
    my-job:
        name: Run MATLAB Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v6
            - name: Set up MATLAB
              uses: matlab-actions/setup-matlab@v3
            - name: Run build
              uses: matlab-actions/run-build@v3